# Generated by Django 3.1.5 on 2021-01-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210113_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_compcatgo',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
