# Generated by Django 3.1.5 on 2021-02-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210223_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='comp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
