# Generated by Django 3.1.5 on 2021-03-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20210316_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockv3',
            name='stock_id',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
