# Generated by Django 3.1.5 on 2021-03-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_stockv3_stock_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='comp_isvalid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_isvalid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stockv3',
            name='stock_isvalid',
            field=models.BooleanField(default=False),
        ),
    ]
