# Generated by Django 3.1.5 on 2021-03-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20210319_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_sn',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
