# Generated by Django 3.1.5 on 2021-03-23 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20210323_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_cate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='item_cate', to='stock.category'),
            preserve_default=False,
        ),
    ]
