# Generated by Django 3.1.5 on 2021-03-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20210323_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockv3',
            name='stock_sn',
            field=models.ForeignKey(limit_choices_to={'item_isvalid': True}, on_delete=django.db.models.deletion.PROTECT, related_name='stockv3_item', to='stock.item'),
        ),
    ]
