# Generated by Django 3.1.5 on 2021-03-12 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_add_comp_emailfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_en', models.CharField(max_length=1, unique=True)),
                ('cate_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_sn', models.CharField(max_length=11)),
                ('item_name', models.CharField(max_length=100)),
                ('item_specmain', models.CharField(max_length=100)),
                ('item_specsub', models.CharField(blank=True, max_length=100, null=True)),
                ('item_cnt', models.IntegerField()),
                ('item_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('stock_addtime', models.DateTimeField(auto_now_add=True)),
                ('stock_updatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stockv3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_change', models.CharField(choices=[('入庫', '入庫'), ('出庫', '出庫')], default='入庫', max_length=10)),
                ('stock_cnt', models.IntegerField()),
                ('stock_currency', models.CharField(choices=[('新台幣', '新台幣'), ('美金', '美金'), ('歐元', '歐元'), ('人民幣', '人民幣')], default='新台幣', max_length=20)),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock_time', models.DateField()),
                ('stock_sign', models.CharField(max_length=20)),
                ('stock_isvalid', models.BooleanField(default=True)),
                ('stock_addtime', models.DateTimeField(auto_now_add=True)),
                ('stock_updatetime', models.DateTimeField(auto_now=True)),
                ('stock_comp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockv3_comp', to='stock.company')),
                ('stock_inaunit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockv3_inaunit', to='stock.inaunit')),
                ('stock_proj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockv3_proj', to='stock.project')),
                ('stock_sn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockv3_item', to='stock.item')),
                ('stock_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockv3_warehouse', to='stock.warehouse')),
            ],
        ),
    ]
