# Generated by Django 3.1.5 on 2021-03-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_category_item_stockv3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_sn',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
