# Generated by Django 3.1.5 on 2021-03-15 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20210312_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='stock_addtime',
            new_name='item_addtime',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='stock_updatetime',
            new_name='item_updatetime',
        ),
        migrations.AddField(
            model_name='item',
            name='item_cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_cate', to='stock.category'),
        ),
    ]
